#!/bin/bash

# vars
NAME=$(basename $0)
USAGE=$(printf "Usage: %s: [-h] TO_NUMBER MESSAGE" $NAME)

# parse optionals args
while getopts 'h' OPTION
do
    case $OPTION in
    h)
        printf "send an SMS to a mobile phone\n\n"
        printf "$USAGE\n\n"
        printf "  TO_NUMBER   international format (like 336xxxxxxxx)\n"
        printf "  MESSAGE     SMS message (like \"this is SMS content\")\n"
        printf "  -h          print this help message\n"
        exit 0
        ;;
    esac
done
shift $(($OPTIND - 1))

# parse fixed args
TO=$1
MSG=$2

# some tests
[ $EUID -ne 0 ] && { printf "ERROR: $NAME needs to be run by root\n" 1>&2; exit 1; }
[ $# -ne 2 ] && { printf "$USAGE\n" 1>&2; exit 1; }

# build SMS file
FILE=`mktemp /tmp/"$NAME"_XXXXXX`
echo "To: $TO" > $FILE
echo "" >> $FILE
echo -e -n "$MSG" >> $FILE

# transfert to send directory
chown smsd:smsd $FILE
mv $FILE /var/spool/sms/outgoing/
